### ISSUE TITLE
Move map up

### ISSUE THREAD

**Issue by xivk** [bikedataproject/website#37]
@Driesvanransbeeck Can you verify if this is ok:

https://staging.bikedataproject.org/datamap#10/50.8454/4.3525

**Comment by Driesvanransbeeck** [comment]
Yes, much better! One remark: given the full screen size of the map, it's currently hard to find out that there's text below the map. Can we reduce the height of the map to make it easier to scroll down @xivk?

**Comment by xivk** [comment]
We probably need another solution to fix the scrolling. Is this issue on mobile? Any suggestions on a fix other than reducing size?

We need to make the data portal map responsive, then we can reduce size.

**Comment by antoinedejonckheere** [comment]
I've started working on a solution on this PR: https://github.com/bikedataproject/website/pull/51 (#51 )
It simply disables the scroll zoom.
The user might still zoom using double click.
I would suggest to add a control button to reset the map to its initial state (otherwise it's simply impossible to zoom out).
Tell me what you think, more than happy to help with Mapbox gl :)
